### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by iurisilvio** [revolunet/pypdftk#2]
I want to use your package but I didn't found it in PyPI.

**Comment by grantmcconnaughey** [comment]
+1 Please release on PyPI

**Comment by revolunet** [comment]
can anyone handle this please ? i'm not a big fan of python packaging :/

**Comment by revolunet** [comment]
similar on NodeJS : https://github.com/ScottONeal/fill-pdf

**Comment by iurisilvio** [comment]
Sure! I did a first release.

https://pypi.python.org/pypi/pypdftk

Can I add you as a package owner in PyPI? If yes, what is your PyPI username?

Of course I can release the next versions, but it is an easy task.

For the first time, I had to register the package:

```
$ python setup.py register
```

Now, just package and release:

```
$ python setup.py sdist upload
```

I did a small change to your setup file, because the classifier was wrong. https://github.com/revolunet/pypdftk/pull/3/files

Thanks for pypdftk, it is really useful to me!

**Comment by revolunet** [comment]
Sorry i dont have pypi username :/
I added you as collab to the repo
Nice to know its useful, thanks !

**Comment by iurisilvio** [comment]
No problem. You can just contact me if you need something in PyPI.

**Comment by revolunet** [comment]
:+1:
