### ISSUE TITLE
Is it possible to just return the pdf file without saving it?

### ISSUE THREAD

**Issue by jandetlefsen** [revolunet/pypdftk#21]
I want to create an API that just serves a PDF as Base64 for a browser app. Do i always have to save the file and then process it or can this library just return the data? Would like to not store any customer data if possible.

**Comment by revolunet** [comment]
Hi, this tool always use physical file, but it could be upgraded to use streams too

**Comment by revolunet** [comment]
btw, as the methods return the pdf path, you can also serve it and delete it
