### ISSUE TITLE
path format

### ISSUE THREAD

**Issue by henryjames92** [revolunet/pypdftk#25]
Hi,

I'm not an experienced coder, and I'm trying to use this package. I noted that there is an issue with python 3 that is being looked at. 

However, I am also having an issue using the path. I noted that the program doesn't like it when I use the whole path starting with C:\ . It also doesn't like it when I just use the name of the file, which is in the same folder as the scratch file. I was hoping I could get some more direction in terms of what this should look like.

**Comment by iyoossaev** [comment]
WORKS:
template_file = template.pdf
pypdftk.fill_form(template_file, csv_data, output_file)

DOESNT WORK:
template_file = os.path.join(os.getcwd(), 'template.pdf')
pypdftk.fill_form(template_file, csv_data, output_file)

I have tried 11 ways of converting the string to path, as well encoding/decoding it. Why doesn't it work?
