### ISSUE TITLE
pypi release 0.4

### ISSUE THREAD

**Issue by rtpm** [revolunet/pypdftk#28]
Hello, can you please release 0.4 version to pypi ?

Thanks!

**Comment by revolunet** [comment]
hello, i finally managed to push 4.0 to pypi. can you please check if its ok fo you ?

thanks

**Comment by abathur** [comment]
@revolunet Can you also tag/release this on github? (It looks like you released from d394427ea253d2daf726f9a3ef64c8d2fd27710d, though I haven't tried to validate that the contents of the source on pypi match the repo at this commit.)

Seeing a mis-match in most-recent release between pypi and github (especially given the time lapse between version 0.3 and 0.4) made me worry that someone had compromised the pypi account and pushed an unauthorized release.

**Comment by revolunet** [comment]
Done, sorry for the delay
