### ISSUE TITLE
Possible update to README.md

### ISSUE THREAD

**Issue by tomasagjr** [revolunet/pypdftk#45]
As of this writing, the section [pdftk path](https://github.com/revolunet/pypdftk#pdftk-path) of README.md provides the following.
> By default, path is `/usr/bin/pdftk`, but you can override it with the `PDFTK_PATH` environment variable

I would like to suggest the following revision. It's longwinded, I know; but worth it (I think/hope).
> This module, _being a driver_, requires that you already have [pdftk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/) installed. First, the module will look to see if the `PDFTK_PATH` environment variable is set. If it's not set, it'll look in the `/usr/bin` directory. As last resort, it'll simply look in whatever directory it, i.e., the module itself, is located.
Also: Double-check your `PDFTK_PATH` environment variable, and make sure it ends with the filename of the binary itself, e.g., `pdftk` and _not_ just the path to the directory where it is located.
For example (on a Windows machine, where `pdftk` is installed in `C:\Program Files (x86)`)...
If `PDFTK_PATH` is set to `C:\Program Files (x86)\PDFtk\bin`, it will throw the `test call` error; _but_, if you add `pdftk`, i.e., binary's filename, to the end, it will not.
e.g., `C:\Program Files (x86)\PDFtk\bin\pdftk`

Or... you could just add a check for that in the module itself. Maybe something like...
```python
if os.getenv('PDFTK_PATH'):
    PDFTK_PATH = os.getenv('PDFTK_PATH')
    if not PDFTK_PATH.endswith('pdftk'):
        PDFTK_PATH = os.path.join(PDFTK_PATH, 'pdftk')
else:
    PDFTK_PATH = '/usr/bin/pdftk'
    if not os.path.isfile(PDFTK_PATH):
        PDFTK_PATH = 'pdftk'
```

**Comment by revolunet** [comment]
Hi, @tomasagjr , thanks for your suggestion; do you mind making a pull request on the README ?

**Comment by tomasagjr** [comment]
No problem. Will do.
