### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mertz3hack** [revolunet/pypdftk#7]
Could you please provide more examples on using the features of this tool.  It sounds like it is exactly what I need but I am not exactly sure how to write it out.
I am looking to fill in a few forms, flatten only the ones I fill in and overwrite the file I opened once filled in.

I am also getting the error 'must be str, not bytes' and am looking for how to convert?

    strung = 'example.pdf'
    thispath = os.path.abspath(strung)
    print(thispath)
    mypath = pypdftk.get_num_pages(thispath)
    print(mypath)

Traceback (most recent call last):
  File "C:\freeopcua\examples\40T.py", line 41, in <module>
    mypath = pypdftk.get_num_pages(thispath)
  File "C:\Python34\lib\site-packages\pypdftk.py", line 43, in get_num_pages
    for line in run_command([PDFTK_PATH, pdf_path, 'dump_data']):
  File "C:\Python34\lib\site-packages\pypdftk.py", line 37, in run_command
    p = check_output(command, shell=shell)
  File "C:\Python34\lib\site-packages\pypdftk.py", line 24, in check_output
    process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
  File "C:\Python34\lib\subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1104, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by revolunet** [comment]
Looks like pdftk binary is not installed on your system

You have to have pdftk.exe installed and define the environnement variable `PDFTK_PATH` to point to it so the library can find it (see https://github.com/revolunet/pypdftk/blob/master/pypdftk.py#L15)

**Comment by mertz3hack** [comment]
Okay it may not have since I installed via pip


-----Original Message-----

**Comment by iurisilvio** [comment]
I think it must fail with a better message.

Maybe check if the executable exist. Calling `PDFTK_PATH` without parameters exit the process with `exit_code=0`, but it fails if pdftk is not there.
